name: handle_notification
description: A new Flutter plugin.
version: 1.0.0
homepage: https://github.com/knoxpo/handle_notification

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.knoxpo.handle_notification
        pluginClass: HandleNotificationPlugin
